---
abstract: 'MooseX::Getopt, but without implicit option generation'
author:
  - 'Rob Hoelz <rob@hoelz.ro>'
build_requires:
  Capture::Tiny: 0
  Module::Build: 0.3601
  Test::More: 0
  autodie: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Getopt-Explicit
requires:
  MooseX::Getopt: 0
  perl: v5.8.8
resources:
  bugtracker: https://github.com/hoelzro/moosex-getopt-explicit/issues
  homepage: https://github.com/hoelzro/moosex-getopt-explicit
  repository: https://github.com/hoelzro/moosex-getopt-explicit.git
version: 0.01
